version: '3'
services:
  mongo:
    image: mongo:4.2
    volumes:
      - mongo_data:/data/db
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:443"
      - "5000:80"
    links:
      - "mongo"
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "8080:4200"
    links:
      - "server"
volumes:
  mongo_data:
    driver: local